
completion_month_high_score_file_download = 100
completion_month_high_score_web_visit = 100

completion_month_low_score_file_download = 0
completion_month_low_score_web_visit = 1

completion_month_random_score_file_download = 0
completion_month_random_score_web_visit = 2

completion_3month_high_score_file_download = 100
completion_3month_high_score_web_visit = 100

completion_3month_low_score_file_download = 0
completion_3month_low_score_web_visit = 1

completion_3month_random_score_file_download = 9
completion_3month_random_score_web_visit = 10

completion_6month_high_score_file_download = 100
completion_6month_high_score_web_visit = 100

completion_6month_low_score_file_download = 0
completion_6month_low_score_web_visit = 1

completion_6month_random_score_file_download = 15
completion_6month_random_score_web_visit = 12

completion_year_high_score_file_download = 100
completion_year_high_score_web_visit = 100

completion_year_low_score_file_download = 0
completion_year_low_score_web_visit = 1

completion_year_random_score_file_download = 19
completion_year_random_score_web_visit = 20
